name: git tag release

on:
  workflow_dispatch:

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository code
              uses: actions/checkout@v3

            # - name: Approve tag creation
            #   uses: trstringer/manual-approval@v1
            #   with: 
            #     secret: ${{ github.TOKEN }}
            #     approvers: SumptaOj

            - name: Extract Package Version
              id: extract
              run: |
               PACKAGE_VERSION=$(jq -r .version package.json)
               echo "PACKAGE_VERSION=${PACKAGE_VERSION}" >> "$GITHUB_OUTPUT"

            - name: Get The Current Tag
              id: current
              run: echo "GIT_TAG=`echo $(git describe --tags --abbrev=0)`" >> $GITHUB_OUTPUT

            - name: Create tag
              run: |
                PACKAGE_VERSION=${{ steps.extract.outputs.PACKAGE_VERSION }}
                git tag $PACKAGE_VERSION
                git push origin $PACKAGE_VERSION

            
            - name: Create a release
              run: |
                PACKAGE_VERSION=${{ steps.extract.outputs.PACKAGE_VERSION }}
                curl -L \
                  -X POST \
                  -H "Accept: application/vnd.github+json" \
                  -H "Authorization: Bearer ${{ github.TOKEN }}" \
                  -H "X-GitHub-Api-Version: 2022-11-28" \
                  https://api.github.com/repos/${{ github.repository }}/releases \
                  -d '{"tag_name":"${{ steps.extract.outputs.PACKAGE_VERSION }}","target_commitish":"main","name":"${{ steps.extract.outputs.PACKAGE_VERSION }}","body":"Description of the release","draft":false,"prerelease":false,"generate_release_notes":false}'

            - name: Create new release note
              run: |
                curl -L \
                  -X POST \
                  -H "Accept: application/vnd.github+json" \
                  -H "Authorization: Bearer ${{ github.TOKEN }}" \
                  -H "X-GitHub-Api-Version: 2022-11-28" \
                  https://api.github.com/repos/${{ github.repository }}/releases/generate-notes \
                  -d '{"tag_name":"${{ steps.extract.outputs.PACKAGE_VERSION }}","target_commitish":"main","previous_tag_name":"${{ steps.current.outputs.GIT_TAG }}"}'