name: Git Tag Release

on:
  workflow_dispatch:

jobs:
    tag_and_release:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository code
              uses: actions/checkout@v3

            - name: Approve tag creation
              uses: trstringer/manual-approval@v1
              with: 
                secret: ${{ github.TOKEN }}
                approvers: SumptaOj

            - name: Extract Package Version
              id: extract
              run: |
               PACKAGE_VERSION=$(jq -r .version package.json)
               echo "PACKAGE_VERSION=${PACKAGE_VERSION}" >> "$GITHUB_OUTPUT"

            - name: Get The Current Tag
              id: current
              run: echo "GIT_TAG=`echo $(git describe --tags --abbrev=0)`" >> $GITHUB_OUTPUT

            - name: Create tag
              run: |
                PACKAGE_VERSION=${{ steps.extract.outputs.PACKAGE_VERSION }}
                git tag $PACKAGE_VERSION
                git push origin $PACKAGE_VERSION

            - name: Generate release notes
              id: release_notes
              run: |
                previous_tag=$(git describe --abbrev=0 --tags $(git describe --tags --abbrev=0))
                release_notes=$(git log --pretty=format:"%s%n%b" $previous_tag..HEAD)
                echo "::set-output name=release_notes::$release_notes"     
          
            - name: Create release
              uses: actions/create-release@v1
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                tag_name: ${{ github.ref }}
                release_name: Release ${{ github.ref }}
                body: ${{ steps.release_notes.outputs.release_notes }}
        
        
        
        

          
              
  
