name: Build
on: [push]
jobs:
  bump_and_tag:
    name: bump repo version
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Check out code from branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install pip
        run: |
          python -m ensurepip --default-pip
          python -m pip install --upgrade pip
      - name: Install Commitizen
        run: pip install -U commitizen
      - name: Create and Write cz.json
        run: |
          echo 'ewogICJjb21taXRpemVuIjogewogICAgIm5hbWUiOiAiY3pfY29udmVudGlvbmFsX2NvbW1pdHMiLAogICAgInRhZ19mb3JtYXQiOiAiJHZlcnNpb24iLAogICAgInZlcnNpb25fc2NoZW1lIjogInNlbXZlciIsCiAgICAidmVyc2lvbl9wcm92aWRlciI6ICJucG0iCiAgfQp9' | base64 -d > .cz.json
      - name: bump the repository and tag it
        run: |
          git config --global user.email "bot@gmail.com"
          git config --global user.name "Tobi"
          cz bump --yes
      - name: generate the changelog
        run: cz changelog
      - name: remove cz config
        run: rm .cz.json
      - name: commit change log
        run: |
          git add .
          git commit -m "changelog for feature release"
      - name: push the generated tag
        run: |
          PACKAGE_VERSION=$(jq -r .version package.json)
          git config --global user.email "bot@gmail.com"
          git config --global user.name "Tobi"
          git push origin main
          git push origin $PACKAGE_VERSION