name: git tag release

on:
    workflow_dispatch:
        branches:
            main

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository code
              uses: actions/checkout@v2
            
            - name: Check tag repository
              run: |
                echo "PR was checkout Hurray"
                PACKAGE_VERSION=$(jq -r .version package.json)
                echo "PACKAGE_VERSION=${PACKAGE_VERSION}" >> $GITHUB_ENV
                git tag $PACKAGE_VERSION