name: git tag release

on:
    workflow_dispatch:

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository code
              uses: actions/checkout@v3

            - name: Approve tag creation
              uses: trstringer/manual-approval@v1
              with: 
                secret: ${{ github.TOKEN }}
                approvers: SumptaOj
              
            - name: Create tag
              run: |
                PACKAGE_VERSION=$(jq -r .version package.json)
                echo "PACKAGE_VERSION=${PACKAGE_VERSION}"
                git tag $PACKAGE_VERSION
                git push origin $PACKAGE_VERSION

            - name: Create tag release note
              run: |
                curl -L \
                  -X POST \
                  -H "Accept: application/vnd.github+json" \
                  -H "Authorization: Bearer <YOUR-TOKEN>" \
                  -H "X-GitHub-Api-Version: 2022-11-28" \
                  https://api.github.com/repos/OWNER/REPO/releases/generate-notes \
                  -d '{"tag_name":"v1.0.0","target_commitish":"main","previous_tag_name":"v0.9.2","configuration_file_path":".github/custom_release_config.yml"}'