name: git tag release

on:
    workflow_dispatch:

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository code
              uses: actions/checkout@v3
            
            - name: Check tag repository
              run: |
                echo "PR was checked out, Hurray"
                PACKAGE_VERSION=$(jq -r .version package.json)
                echo "PACKAGE_VERSION=${PACKAGE_VERSION}" # Add this line for debugging

            - name: Approve tag creation
              uses: trstringer/manual-approval@v1
              with:
                secret: ${{ github.TOKEN }}
                approvers: SumptaOj
              
            - name: Create tag
              run: |
                PACKAGE_VERSION=$(jq -r .version package.json)
                echo "PACKAGE_VERSION=${PACKAGE_VERSION}"
                git tag $PACKAGE_VERSION
                git push origin $PACKAGE_VERSION
               